
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA ENTERO ID IGUAL KILOBYTE MAYOR_QUE MKDISK PATH SIZE UNITinit : list_commandslist_commands : list_commands commands\n                    | commandscommands : command_mkdisk\n                | command_rmdiskcommand_mkdisk : MKDISK MAYOR_QUE UNITcommand_rmdisk : ENTERO  '
    
_lr_action_items = {'MKDISK':([0,2,3,4,5,7,8,10,],[6,6,-3,-4,-5,-7,-2,-6,]),'ENTERO':([0,2,3,4,5,7,8,10,],[7,7,-3,-4,-5,-7,-2,-6,]),'$end':([1,2,3,4,5,7,8,10,],[0,-1,-3,-4,-5,-7,-2,-6,]),'MAYOR_QUE':([6,],[9,]),'UNIT':([9,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'list_commands':([0,],[2,]),'commands':([0,2,],[3,8,]),'command_mkdisk':([0,2,],[4,4,]),'command_rmdisk':([0,2,],[5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> list_commands','init',1,'p_init','parser_.py',10),
  ('list_commands -> list_commands commands','list_commands',2,'p_list_commands','parser_.py',16),
  ('list_commands -> commands','list_commands',1,'p_list_commands','parser_.py',17),
  ('commands -> command_mkdisk','commands',1,'p_commands','parser_.py',25),
  ('commands -> command_rmdisk','commands',1,'p_commands','parser_.py',26),
  ('command_mkdisk -> MKDISK MAYOR_QUE UNIT','command_mkdisk',3,'p_command_mkdisk','parser_.py',30),
  ('command_rmdisk -> ENTERO','command_rmdisk',1,'p_command_rmdisk','parser_.py',36),
]
